modLoader="javafml"
loaderVersion="[36,)"
license="CC BY-SA"
issueTrackerURL="https://github.com/En0ri4n/Craft-Creator/issues"

[[mods]]
modId="craftcreator"
version="${file.jarVersion}"
displayName="Craft Creator"
logoFile="logo.png"
credits="Traptonian (Arts)"
authors="En0ri4n (Enooow#4595 on Discord!)"
description='''
Craft Creator is a mod that allows you to create your own crafts in Minecraft! (with kubeJS system or just datapacks)
'''

[[dependencies.craftcreator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftcreator]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
